### ISSUE TITLE
Wrong sound explosion on Xevious

### ISSUE THREAD

**Issue by DFL1973** [Gehstock/Mist_FPGA#111]
Compared to MAME videos, the ship explosion (when Solvalou dies) is wrong. The explosion sound is wrong on the bombed enemy structures on the ground too. (maybe both are the same sound sample?)

**Comment by gyurco** [comment]
In MAME sources, there's a note about the cs54xx clock is divided by 6 internally. The MB8842 datasheet (which the cs54xx chip really is) says about a divide by 2 prescaler only. I wonder where this /6 comes from. This surely affects the pitch of the explosions.

**Comment by DFL1973** [comment]
I recorded the sound with the mobile and play at 25% speed. I believe you are correct, the actual sound it´s like a "faint slap", but at the slower speed, it´s something like an explosion.
