### ISSUE TITLE
Jump button on Wonder Boy Arcade Core

### ISSUE THREAD

**Issue by MarkOZLAD** [Gehstock/Mist_FPGA#122]
As Wonder Boy only uses a two direction joystick,  could there be an option added to make the "Up" button on the DB9 joystick to be the second button?

**Comment by gyurco** [comment]
You can remap the DB9 joystick buttons, see the example at the end of:
https://github.com/mist-devel/mist-board/wiki/USBJoystickMapping#example-mappings

**Comment by MarkOZLAD** [comment]
Ok I was able to map it but only in the main part of the mist.ini.  Any idea what tag I should use to make the configuration only for wonder boy on sega system 1?

**Comment by gyurco** [comment]
[WBOY] doesn't work?
It's in the left of the OSD.

**Comment by MarkOZLAD** [comment]
Ok the issue was that I was launching the "SegaSys1.rbf" instead of the "Wonder Boy (set 1, 315-5177).arc".  So I have that working now.

I ended up going with the following in my mist.ini

[WBOY]
joystick_remap=00db,0000,1,2,4,10,20
joystick_remap=00db,0001,1,2,4,10,20

Thanks for the assistance.
