### ISSUE TITLE
Wonder Boy Arcade on Mist is showing in incorrect resolution

### ISSUE THREAD

**Issue by MarkOZLAD** [Gehstock/Mist_FPGA#123]
I have both a Mist and a genuine arcade PCB for Wonder Boy.  When I run my arcade PCB it the wonder boy image up the full width of the screen.  When I run Wonder Boy on the Mist it is taking up about three quarters of the screen.  I believe this might be contributing to the scrolling being choppy when sprinting.

Note: My arcade is using an RGB modded TV set that doesn't have a horizontal width setting so I have not adjusted the width.
![Wonder Boy Filling Screen Width - genuine PCB](https://user-images.githubusercontent.com/26852879/123498492-8839bb00-d673-11eb-90d7-cd2df8bb65c5.jpg)
![Wonder Boy not filling screen width](https://user-images.githubusercontent.com/26852879/123498499-8ec83280-d673-11eb-9e78-8eed5485b4e6.jpg)

**Comment by gyurco** [comment]
The cores from this author doesn't implement the original video timings, but some imaginary ones. Correcting it is not trivial, since it affects other parts (background and sprite generator).

**Comment by gyurco** [comment]
I've did some adjustments
[segasys1-test1.zip](https://github.com/Gehstock/Mist_FPGA/files/6720380/segasys1-test1.zip)
 according to the schematics of Up'n'Down and Starjacker. Unfortunately there's a PAL chip which I don't see inside, so some values are guessed. But it fills the whole screen. It's attached, test it please.

**Comment by MarkOZLAD** [comment]
> I've did some adjustments

Adjustements look good. 

> The cores from this author doesn't implement the original video timings, but some imaginary ones. Correcting it is not trivial, since it affects other parts (background and sprite generator).

That's a shame.  The game is very playable,  using the DB9 joystick I don't detect any lag.  The scrolling of the background the only major issue and it's really distracting for someone used to the real hardware.  Surely not implementing the correct timings defeats the purpose of using an FPGA?

Thank you for your efforts.  Even if not perfect it will allow people to have a good experience with my favourite game.
