### ISSUE TITLE
IremM72 not starting

### ISSUE THREAD

**Issue by squidrpi** [Gehstock/Mist_FPGA#142]
All M72 games only get to the "ROM OK RAM OK" message and then stops.

Using 0.247 roms on v1.4 MIST.

**Comment by squidrpi** [comment]
Yes "Diagnostic Test" is defaulting to on for me and "Flip picture" defaults to on also. Core running OK now.

Nice work! One of my all time favs, thanks.

**Comment by gyurco** [comment]
The MRAs missing the colon separator in the switches default tag, so the MRA tool doesn't include the defaults in the ARC file.

**Comment by squidrpi** [comment]
You mean comma? If I've read the code correctly:
The mra code:
n = sscanf(attr->value, "%X,%X,%X,%X", &a, &b, &c, &d);
checks for commas. So the MRA samples are wrong too, some use spaces others use comma.

**Comment by gyurco** [comment]
Yes, sorry, they miss the comma.

**Comment by squidrpi** [comment]
Is the firmware parsing the switches correctly? I can't figure out why, for example, the RType arc says 0 for Crafts(3) & Difficulty (Normal) but on the MIST it says Crafts (4) & Difficulty (Difficult).

**Comment by gyurco** [comment]
I'm sure my defaults was Diagnostics OFF for example.
What's in your RTYPE.CFG?

**Comment by squidrpi** [comment]
I deleted the RTYPE.CFG so it's only using the ARC. 
I've also made a patch for MRA to fix the space/comma handling bug but sebdel doesn't appear to update it anymore, Jotego also put in a different patch. Can you fork it and make it the official MIST version?

If I don't change anything and save the settings, the RTYPE.CFG contains:
[CFG]
STATUS=0xc0a0000

**Comment by squidrpi** [comment]
I was using an older version of MRA. Crap!
ARC switches are now correct with the latest MRA version. RType should be Normal by default. I'll check the others and submit changes.
I'll sort out the MRA source code and fix it up to handle spaces.
