### ISSUE TITLE
A graphic glitch on Jupiter ACE core

### ISSUE THREAD

**Issue by desUBIKado** [Gehstock/Mist_FPGA#2]
You can see it here:  http://www.atari-forum.com/viewtopic.php?f=115&t=32258&start=50#p368119

**Comment by gustinian** [comment]
I have noticed a graphical glitch too with the Jupiter Ace core on MiST. For instance, on bootup if you type in the command 'WORDS' for a listing of Forth's initial Dictionary, an outer column of the screen is omitted and one column is repeated mid way. If memory serves, I think it might have been column 16 which might provide a clue. Your efforts are greatly appreciated.

**Comment by Gehstock** [comment]
No Interest on this Core, someone other will fix that
