### ISSUE TITLE
Konami Scramble Hardware - Bottom of video is cut off

### ISSUE THREAD

**Issue by sajattack** [Gehstock/Mist_FPGA#64]
I discovered this issue while working on a Calipso port. If you look at pictures of Calipso, there is a section at the very bottom that shows your level and how much air you have left, and this is missing in the MiST version. 
![](https://media.discordapp.net/attachments/665637657061359635/666408085434269727/1181242065238.png)

![](https://cdn.discordapp.com/attachments/665637657061359635/666408120339267619/20200113_141911-screen.png)

Apparently it applies to other games as well. Sorgelig fixed this when he did his own port, available here: https://github.com/MiSTer-devel/Arcade-Scramble_MiSTer

**Comment by gyurco** [comment]
Thanks, I've noticed it, too. Meanwhile Scramble got a big update.

**Comment by Gehstock** [comment]
Allready fixed
