### ISSUE TITLE
Williams/Robotron cores and joystick swapping

### ISSUE THREAD

**Issue by squidrpi** [Gehstock/Mist_FPGA#69]
The Williams/Robotron cores need the joystick swapping, seems to default to the wrong way around. The Williams/Defender cores aren't affected.

**Comment by gyurco** [comment]
Joystick swap is in the menu.

**Comment by squidrpi** [comment]
Yes but it defaults the wrong way around compared to the other arcade cores.

**Comment by gyurco** [comment]
Most arcade cores treat both joystick the same way, but Robotron must use both separately. Compared to e.g. Genesis, is it different?

**Comment by squidrpi** [comment]
Genesis doesn't need the swap, PCENGINE does.

**Comment by gyurco** [comment]
Genesis swaps by default, so I would say PCE behaviour is correct. However there's no correct behaviour. Here's why:
https://github.com/mist-devel/mist-firmware/issues/37
But I think you knows about that.

**Comment by gyurco** [comment]
The conclusion: every arcade with the new input module will need swap activated for the first USB controller (if there's a swap option). But if it the controllers will be un-swapped in the firmware finally, then it could be turned off in the cores.

**Comment by squidrpi** [comment]
Understood.
