### ISSUE TITLE
New Firmware fixes for MIST.INI appears to have problems?

### ISSUE THREAD

**Issue by squidrpi** [Gehstock/Mist_FPGA#70]
With the SPLAT ROM I can't get the remap working:

[SPLAT]
;(Up/Down/Left/Right, Fire Direction X/B/Y/A, OSD Y+A)
joystick_remap=0583,2060,1,2,4,8,80,20,10,40,400,800,1000,2000

It just seems to ignore the remap settings. Other remaps I've used for Defender, Robotron etc work fine. Can't figure what the issue is.

Moved the remap around the mist.ini and removed comments but no difference. Perhaps it's because the name is less than 8 chars?

Can't figure out how to debug the Mist firmware without a mist. Is this possible?

**Comment by gyurco** [comment]
Padding the core name with spaces wasn't the best idea. Will do it differently.

**Comment by gyurco** [comment]
This is fixed already with firmware 200214.

**Comment by squidrpi** [comment]
Thanks gyurco, working fine now.
