### ISSUE TITLE
MRA files for System1

### ISSUE THREAD

**Issue by DFL1973** [Gehstock/Mist_FPGA#88]
Hey guys, the MRA files to generate the ROMs for the Sega System 1 appears to be broken.

There is a warning that prevents to generate the "MOD=" in the arc file
warning: unexpected token in rom node: rom

Ok, just need to move the line "<rom index=1>" before the "<rom index=0>"

Anyway, I can't get the correct MD5 (tried a LOT of different zips), so the games doesn't work.

Is this games supposed to work?

**Comment by jotego** [comment]
I think the MRA tool calculates md5 in a different way from MiSTer. The code in the MRA files is meant for MiSTer.

**Comment by Gehstock** [comment]
Core is still WIP, Video and SDRAM must be changed

**Comment by Gehstock** [comment]
the MRA tool shows the correct md5 so you can correct it in the MRA File

`warning: md5 mismatch! (found: d0279c92130f52cc711029e531c647a4, expected: 15ab241d9f6780f41721916f46e7d4fa)`

**Comment by Gehstock** [comment]
Core is still WIP, Video and SDRAM must be changed

the MRA tool shows the correct md5 so you can correct it in the MRA File

`warning: md5 mismatch! (found: d0279c92130f52cc711029e531c647a4, expected: 15ab241d9f6780f41721916f46e7d4fa)`

Btw. any News about the Forum?

**Comment by Gehstock** [comment]
the MRA are Changed

**Comment by DFL1973** [comment]
Thanks. I generated some ROMs, but there are some problems with the video, I guess. (maybe it was you are talking about the WIP and the SDRAM).

Thanks,  I will wait for the "final" RBF. Pitfall II is one of my favorite games.

Minor note: I believe Choplifter is kind of the same hardware.

![IMG_1967-24-05-20-16-49](https://user-images.githubusercontent.com/52256314/82763580-3c1ca700-9ddf-11ea-8f51-6c50d14c32f0.JPG)
![IMG_1968-24-05-20-16-49](https://user-images.githubusercontent.com/52256314/82763582-3cb53d80-9ddf-11ea-8941-10afc854ea25.JPG)
![IMG_1970-24-05-20-16-49](https://user-images.githubusercontent.com/52256314/82763583-3d4dd400-9ddf-11ea-98dc-dd0bec3a81e0.JPG)
![IMG_1966-24-05-20-16-49](https://user-images.githubusercontent.com/52256314/82763584-3e7f0100-9ddf-11ea-860a-0e7b3cdd2160.JPG)

**Comment by Gehstock** [comment]
there are a lot more
https://github.com/mamedev/mame/blob/master/src/mame/drivers/system1.cpp

**Comment by DFL1973** [comment]
Nice! Teddy boy and Wonderboy are great too!

**Comment by DFL1973** [comment]
Is the System 1 finished? Still doesn't work for me, similar screens as above with the last published RBF

**Comment by Gehstock** [comment]
Remove the code until completion to avoid confusion
