### ISSUE TITLE
Information about button mapping

### ISSUE THREAD

**Issue by jotego** [Gehstock/Mist_FPGA#92]
I have tried to run a few arcades but couldn't get the games to start. Where are the insert coin/1P start buttons mapped to? Is it the keyboard, MiST buttons, some gamepad button?

Could that information be added to the README files?

Thank you

**Comment by DFL1973** [comment]
MAME style:
keyboard 5 for coins, 1 for start 1P, 2 for 2P.
CTRL, ALT, Space for buttons, arrow keys as movement

**Comment by Gehstock** [comment]
Most(all) Cores should use ESC for Coin and F1/F2 for Start
