### ISSUE TITLE
Wrong colours on Zaxxon

### ISSUE THREAD

**Issue by DFL1973** [Gehstock/Mist_FPGA#99]
After the merge, the Zaxxon is showing some weird colours.

**Comment by gyurco** [comment]
Did you re-create the ROM file from the MRA?

**Comment by DFL1973** [comment]
Yes, all three games have wrong colours with the MRAs supplied.

**Comment by gyurco** [comment]
The latest MRA.EXE is buggy on Windows. Try this one:
https://github.com/sebdel/mra-tools-c/blob/6b1b300bfe370d46c6361c764133254580effa00/release/windows/mra.exe

**Comment by DFL1973** [comment]
Yes, this fixes my issue, sorry, I didn't know about the last MRA.exe.
